/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-03-02 08:47:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import com.mkj.entities.Doctor;
import java.util.List;
import com.mkj.dao.DAOImpl;

public final class DoctorConsole_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.mkj.dao.DAOImpl");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.mkj.entities.Doctor");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Wellness Pollyclinic</title>\r\n");
      out.write("<link rel=\"icon\" href=\"wellicon.ico\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".mylink {\r\n");
      out.write("\t\r\n");
      out.write(" \t position: relative;\r\n");
      out.write("display: inline-block;\r\n");
      out.write("transition: .3s;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("  \r\n");
      out.write("  box-shadow: none;\r\n");
      out.write("  color: blue;\r\n");
      out.write("  padding:none;\r\n");
      out.write("  position: none;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  text-transform: none;\r\n");
      out.write("  top: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.blueTable {\r\n");
      out.write("  border: 1px solid #1C6EA4;\r\n");
      out.write("  background-color: #DFEEDC;\r\n");
      out.write("  width: 101%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable td, table.blueTable th {\r\n");
      out.write("  border: 3px solid #210351;\r\n");
      out.write("  padding: 7px 4px;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable tbody td {\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable tr:nth-child(even) {\r\n");
      out.write("  background: #72F5F4;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable thead {\r\n");
      out.write("  background: #09A496;\r\n");
      out.write("  background: -moz-linear-gradient(top, #46bbb0 0%, #21ada0 66%, #09A496 100%);\r\n");
      out.write("  background: -webkit-linear-gradient(top, #46bbb0 0%, #21ada0 66%, #09A496 100%);\r\n");
      out.write("  background: linear-gradient(to bottom, #46bbb0 0%, #21ada0 66%, #09A496 100%);\r\n");
      out.write("  border-bottom: 2px solid #444444;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable thead th {\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: #FFFFFF;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-left: 2px solid #D0E4F5;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable thead th:first-child {\r\n");
      out.write("  border-left: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.blueTable tfoot {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: #FFFFFF;\r\n");
      out.write("  background: #D0E4F5;\r\n");
      out.write("  background: -moz-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);\r\n");
      out.write("  background: -webkit-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);\r\n");
      out.write("  background: linear-gradient(to bottom, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);\r\n");
      out.write("  border-top: 2px solid #444444;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable tfoot td {\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable tfoot .links {\r\n");
      out.write("  text-align: right;\r\n");
      out.write("}\r\n");
      out.write("table.blueTable tfoot .links a{\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  background: #1C6EA4;\r\n");
      out.write("  color: #FFFFFF;\r\n");
      out.write("  padding: 2px 8px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "UserHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<form action=\"doctorBean.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Name </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"doctorName\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Branch </td>\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t<select name=\"branch\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Audiologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Allergist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Anesthesiologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Cardiologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Dentist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Dermatologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Endocrinologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Epidemiologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Gynecologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Immunologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Neurologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Neurosurgeon</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Orthopedic  </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>ENT Specialist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Pediatrician-child </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Urologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>nephrologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Gestrologist </option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>General Physician </option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Licence Number </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"licenceNumber\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Fees </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"fees\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Clinic Fees </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"clinicfees\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Address </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"address\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Phone Number </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"phoneNumber\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Adhar Number </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"text\" name=\"adharNumber\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Status to Our Center </td>\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t<select name=\"doctorStatus\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>true</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>false</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Info </td>\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" row=\"5\" col=\"8\" name=\"doctorInfo\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> Doctor Timings </td>\r\n");
      out.write("\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"doctorTimings\" placeholder=\"All Days 8:00 AM to 11:30 AM\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"submit\" value=\"Add Doctor\"> </td>\r\n");
      out.write("\t\t\t\t\t<td> <input type=\"reset\"> </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		DAOImpl dao = new DAOImpl();
		
		List<Doctor> doctors = dao.getAllDoctor();
		
		Iterator<Doctor> itr = doctors.iterator();
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"blueTable\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<th>Doctor Name</th>\r\n");
      out.write("\t\t\t<th>Doctor Branch</th>\r\n");
      out.write("\t\t\t<th>Licence Number</th>\r\n");
      out.write("\t\t\t<th>Fees </th>\r\n");
      out.write("\t\t\t<th>Clinic Fees </th>\r\n");
      out.write("\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t<th>Phone Number </th>\r\n");
      out.write("\t\t\t<th>Adhar Number</th>\r\n");
      out.write("\t\t\t<th>Doctor Status</th>\r\n");
      out.write("\t\t\t<th>Doctor Info</th>\r\n");
      out.write("\t\t\t<th>Doctor Timings</th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<th>Edit</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t");

				while(itr.hasNext())
				{
					Doctor temp = itr.next();
					
					String doctorName = temp.getDoctorName();
					String branch = temp.getBranch();
					String licenece = temp.getLicenceNumber();
					int fees = temp.getFees();
					int clinicfees = temp.getClinicfees();
					String address = temp.getAddress();
					long phone = temp.getPhoneNumber();
					long adhar = temp.getAdharNumber();
					boolean status = temp.isDoctorStatus();
					String docInfo = temp.getDoctorInfo();
					String docTiming = temp.getDoctorTimings();
					
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(doctorName );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(branch );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(licenece );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(fees );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(clinicfees );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(address );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(phone );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(adhar );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(status );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(docInfo );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> ");
      out.print(docTiming );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td> <a href=\"EditDoctor.jsp?name=");
      out.print(doctorName);
      out.write("&docTime=");
      out.print(docTiming);
      out.write("&fees=");
      out.print(fees);
      out.write("&address=");
      out.print(address);
      out.write("&phone=");
      out.print(phone);
      out.write("&status=");
      out.print(status);
      out.write("&clinicfees=");
      out.print(clinicfees);
      out.write("\" class=\"mylink\">edit</a> </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

				}//end while
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "AllFooter.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
